# Generated by Django 6.0.3 on 2026-04-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso_code', models.CharField(help_text='Language code according to ISO 639-3', max_length=10, primary_key=True, serialize=False, verbose_name='ISO code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Part of speech',
                'verbose_name_plural': 'Parts of speech',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Relation type',
                'verbose_name_plural': 'Relation types',
            },
        ),
        migrations.CreateModel(
            name='Synset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=1000, verbose_name='definition')),
                ('status', models.IntegerField(choices=[(0, 'Unverified'), (-1, 'Rejected'), (1, 'Accepted')], default=0)),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='display_name')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.partofspeech', verbose_name='part of speech')),
            ],
            options={
                'verbose_name': 'synset',
                'verbose_name_plural': 'synsets',
            },
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='lemma')),
                ('lexicalised', models.BooleanField(default=True, verbose_name='lexicalised')),
                ('synset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lex.synset', verbose_name='synset')),
            ],
            options={
                'verbose_name': 'lemma',
                'verbose_name_plural': 'lemmas',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Example sentence showing typical usage', max_length=1000, verbose_name='example')),
                ('synset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lex.synset', verbose_name='Synset')),
            ],
            options={
                'verbose_name': 'example',
                'verbose_name_plural': 'examples',
            },
        ),
        migrations.CreateModel(
            name='Wordnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'wordnet',
                'verbose_name_plural': 'wordnets',
            },
        ),
        migrations.AddField(
            model_name='synset',
            name='wordnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.wordnet'),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.relationtype')),
                ('synset_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lex.synset')),
                ('synset_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lex.synset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('synset_from', 'synset_to', 'type'), name='unique_relation', violation_error_message='Relation already defined')],
            },
        ),
    ]
