# Generated by Django 5.2.11 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='display_name',
            field=models.CharField(default='no_display_name', max_length=100, verbose_name='display_name'),
        ),
    ]
