# Generated by Django 5.2.11 on 2026-09-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lex', '0013_merge_20260904_0804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('target_deleted', 'Target Deleted')], default='active', max_length=30)),
                ('source_synset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_assignments', to='lex.synset')),
                ('target_synset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_assignments', to='lex.synset')),
                ('target_wordnet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lex.wordnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
