# Generated by Django 5.2.11 on 2026-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0003_historicalexample_historicallanguage_historicallemma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrelation',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='historicalsynset',
            name='display_name',
        ),
    ]
