# Generated by Django 5.2.11 on 2026-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0004_remove_historicalrelation_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsynset',
            name='change_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
