# Generated by Django 5.2.11 on 2026-07-09 12:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0005_historicalsynset_change_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemma',
            name='synset',
        ),
        migrations.AddField(
            model_name='historicalpartofspeech',
            name='short_name',
            field=models.CharField(default='n', max_length=1, verbose_name='short name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsynset',
            name='lexicalised',
            field=models.BooleanField(default=True, verbose_name='lexicalised'),
        ),
        migrations.AddField(
            model_name='historicalsynset',
            name='princeton_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Princeton Wordnet ID'),
        ),
        migrations.AddField(
            model_name='partofspeech',
            name='short_name',
            field=models.CharField(default='n', max_length=1, verbose_name='short name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synset',
            name='lexicalised',
            field=models.BooleanField(default=True, verbose_name='lexicalised'),
        ),
        migrations.AddField(
            model_name='synset',
            name='princeton_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Princeton Wordnet ID'),
        ),
        migrations.CreateModel(
            name='HistoricalWord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='lemma')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.language', verbose_name='language')),
                ('pos', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.partofspeech', verbose_name='part of speech')),
            ],
            options={
                'verbose_name': 'historical word',
                'verbose_name_plural': 'historical words',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='lemma')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.language', verbose_name='language')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.partofspeech', verbose_name='part of speech')),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
            },
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.synset', verbose_name='Synset')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lex.word', verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('synset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.synset', verbose_name='Synset')),
                ('word', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'historical sense',
                'verbose_name_plural': 'historical senses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='HistoricalLemma',
        ),
        migrations.DeleteModel(
            name='Lemma',
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('text', 'language', 'pos'), name='unique_word', violation_error_message='Word already defined'),
        ),
        migrations.AddConstraint(
            model_name='sense',
            constraint=models.UniqueConstraint(fields=('word', 'synset'), name='unique_sense'),
        ),
    ]
