# Generated by Django 5.2.11 on 2026-07-28 09:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0006_remove_lemma_synset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalexample',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexample',
            name='synset',
        ),
        migrations.CreateModel(
            name='HistoricalSenseExample',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.CharField(help_text='Example sentence illustrating the meaning of a word in a specific sense', max_length=1000, verbose_name='example')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.sense', verbose_name='Sense')),
            ],
            options={
                'verbose_name': 'historical sense example',
                'verbose_name_plural': 'historical sense examples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSynsetExample',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.CharField(help_text='Example sentence illustrating synset meaning', max_length=1000, verbose_name='example')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('synset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.synset', verbose_name='Synset')),
            ],
            options={
                'verbose_name': 'historical synset example',
                'verbose_name_plural': 'historical synset examples',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SenseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Example sentence illustrating the meaning of a word in a specific sense', max_length=1000, verbose_name='example')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lex.sense', verbose_name='Sense')),
            ],
            options={
                'verbose_name': 'sense example',
                'verbose_name_plural': 'sense examples',
            },
        ),
        migrations.CreateModel(
            name='SynsetExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Example sentence illustrating synset meaning', max_length=1000, verbose_name='example')),
                ('synset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lex.synset', verbose_name='Synset')),
            ],
            options={
                'verbose_name': 'synset example',
                'verbose_name_plural': 'synset examples',
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='HistoricalExample',
        ),
    ]
