# Generated by Django 5.2.11 on 2026-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0007_remove_historicalexample_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsense',
            name='comment',
            field=models.CharField(default='', help_text='Additional information on word sense', max_length=1000, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='sense',
            name='comment',
            field=models.CharField(default='', help_text='Additional information on word sense', max_length=1000, verbose_name='comment'),
        ),
    ]
