# Generated by Django 5.2.11 on 2026-08-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0008_historicalsense_comment_sense_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsynset',
            name='copied_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lex.synset'),
        ),
        migrations.AddField(
            model_name='synset',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_synsets', to='lex.synset'),
        ),
        migrations.AlterField(
            model_name='historicalsense',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Additional information on word sense', max_length=1000, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='historicalsynset',
            name='status',
            field=models.CharField(choices=[('stub', 'Stub'), ('draft', 'Draft'), ('complete', 'Complete'), ('reviewed', 'Reviewed')], default='stub'),
        ),
        migrations.AlterField(
            model_name='sense',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Additional information on word sense', max_length=1000, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='synset',
            name='status',
            field=models.CharField(choices=[('stub', 'Stub'), ('draft', 'Draft'), ('complete', 'Complete'), ('reviewed', 'Reviewed')], default='stub'),
        ),
    ]
