# Generated by Django 5.2.11 on 2026-08-18 06:48

from django.db import migrations


def migrate_status_to_draft(apps, schema_editor):
    Synset = apps.get_model("lex", "Synset")
    Synset.objects.all().update(status="draft")

def reverse_migrate_status(apps, schema_editor):
    Synset = apps.get_model("lex", "Synset")
    Synset.objects.all().update(status="0")


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0009_historicalsynset_copied_from_synset_copied_from_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_status_to_draft,
            reverse_migrate_status,
        ),
    ]
