# Generated by Django 5.2.11 on 2026-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0010_migrate_synset_status_to_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsenseexample',
            name='text',
            field=models.CharField(blank=True, help_text='Example sentence illustrating the meaning of a word in a specific sense', max_length=1000, verbose_name='example'),
        ),
        migrations.AlterField(
            model_name='historicalsynsetexample',
            name='text',
            field=models.CharField(blank=True, help_text='Example sentence illustrating synset meaning', max_length=1000, verbose_name='example'),
        ),
        migrations.AlterField(
            model_name='senseexample',
            name='text',
            field=models.CharField(blank=True, help_text='Example sentence illustrating the meaning of a word in a specific sense', max_length=1000, verbose_name='example'),
        ),
        migrations.AlterField(
            model_name='synsetexample',
            name='text',
            field=models.CharField(blank=True, help_text='Example sentence illustrating synset meaning', max_length=1000, verbose_name='example'),
        ),
    ]
