# Generated by Django 5.2.11 on 2026-08-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0010_migrate_synset_status_to_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwordnet',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='wordnet',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
