# Generated by Django 5.2.11 on 2026-09-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0011_alter_historicalsenseexample_text_and_more'),
        ('lex', '0011_alter_historicalwordnet_name_alter_wordnet_name'),
    ]

    operations = [
    ]
