# Generated by Django 5.2.11 on 2026-08-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lex", "0011_alter_historicalsenseexample_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsynset",
            name="princeton_id",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Princeton Wordnet ID",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="display_name",
            field=models.CharField(
                default="no_display_name", max_length=270, verbose_name="display_name"
            ),
        ),
        migrations.AlterField(
            model_name="synset",
            name="princeton_id",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Princeton Wordnet ID",
            ),
        ),
    ]
