# Generated by Django 5.2.11 on 2026-09-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0011_alter_historicalwordnet_name_alter_wordnet_name'),
        ('lex', '0012_alter_historicalsynset_princeton_id_and_more'),
    ]

    operations = [
    ]
