# Generated by Django 5.2.11 on 2026-09-29 02:22

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("lex", "0013_merge_20260904_0804"),
    ]

    operations = [
        UnaccentExtension(),
    ]
